### PR TITLE
Add support for containerd and dynamically link correct socket into t…

### PR DESCRIPTION
**Pull request by zvn**
…he internal socket path

### CODE REVIEW

**Comment by terylt** [comment]
Hi York,  

I have a few concerns with this commit. 
1.) what's the goal of this PR?
2.)  It seems like the commit will always rename any sock passed in through CRI_PATH to `/var/run/cri.sock`.  Am I correct on this?  If so, I'm not sure that we want to do this renaming because it's one of the ways in which we tell what the runtime is.
3.)  I believe docker.sock is the default that sysdig looks for if it doesn't get a sock.   Does the docker sock now have to be passed in at all times using the CRI_PATH?  Because it looks like if it isn't passed in then, `-p /var/run/cri.sock` will always be passed into the sysporter regardless of whether CRI_PATH is set.  And does this work?
4.)  Back when I was debugging a similar issue on IBM Cloud's k8s, there were two socks.  One was the docker.sock, and the other was the containerd.sock.   It turned out the cloud had switched runtimes but both socks were still there. 
5.)  What does the INTERNAL_CRI_PATH value provide?
6.)  if CRI_PATH == INTERNAL_CRI_PATH, won't the softlink overwrite itself?

@araujof  thoughts?

**Comment by zvn** [comment]
Hi Teryl,

1.) what's the goal of this PR?
    To make the collector being able to support containerd. As far as I know, containerd.sock and crio.sock both implements the same interface(please correct me if I was wrong,) the CRI interface. So in sysdig library it took cri implementation to support both (crio and cri type.)

2.) It seems like the commit will always rename any sock passed in through CRI_PATH to /var/run/cri.sock. Am I correct on this? If so, I'm not sure that we want to do this renaming because it's one of the ways in which we tell what the runtime is.
I can refine it. Originally I want to simplify the behavior inside collector binary, to let it just accept a universal CRI compatible domain socket as the input. Then the entrypoint should configure it correctly to make it work. In this implementation, I am still able to see the CONTAINERD as the runtime type. May I know if I miss anything here?

"container":{"id":"7d8e23164bf4","image":"qradv-docker-local.artifactory.swg-devops.com/neuromancer/neurostore:b3bd80a:b3bd80a","imageid":"daae29cc495593669f3e2a21ae44acacf8f9d7c173f206c012c2993113546086","name":"neurostore-wjwilson-dev1","privileged":0,"type":"**CONTAINERD**"}

I will prepare another implementation of the fix to let you see if it's better. I will add a new parameter (CONTAINERD_PATH) similar to CRI_PATH as the config option for sysporter, then let the sysporter binary decide which should be loaded.

3.) I believe docker.sock is the default that sysdig looks for if it doesn't get a sock. Does the docker sock now have to be passed in at all times using the CRI_PATH? Because it looks like if it isn't passed in then, -p /var/run/cri.sock will always be passed into the sysporter regardless of whether CRI_PATH is set. And does this work?

No, I didn't modify anything related to the docker socket. Just replacing CRI_PATH to a fixed one that we will link either CRIO or containerd in the entrypoint script.

4.) Back when I was debugging a similar issue on IBM Cloud's k8s, there were two socks. One was the docker.sock, and the other was the containerd.sock. It turned out the cloud had switched runtimes but both socks were still there.
I didn't see that situation happening in my environments.. In the ibmcloud cluster, there's only one containerd socket for us. The docker.sock is just an empty folder inside the container(which means no available socket could be mounted in the host)

5.) What does the INTERNAL_CRI_PATH value provide?
Just a variable to indicate where can we find the cri.sock, a universal entry for the cri-compatible domain socket for sysporter to set the CRI path to the sysdig library.

6.) if CRI_PATH == INTERNAL_CRI_PATH, won't the softlink overwrite itself?
hmm... I think the ln command should report File Exists error there?

**Comment by zvn** [comment]
@terylt I made the changes based on the suggestion from you and @araujof. Basically the new environmental variable is removed, and it supports container runtime auto-detection when CRI_PATH is empty.

**Comment by terylt** [comment]
Hi York, 

This is starting to look really good!  I just have a couple more quick comments/questions for change:

1.)  What is the DETECTED_CRI_PATH variable for? I don't see it get set anywhere but it's getting passed into the docker entrypoint.   I'm just wondering if it is something that was left in accidentally?
2.)  Can we make it so that it checks for all three `socks`  and provides a WARNING if more than one is present?  You could have multiple if statements:

```
if [ ! -z "${CRI_PATH}" ] ; then
    echo "Adopt CRI_PATH: ${CRI_PATH}"
else
  numSocks=0
   if [ -S "/host/var/run/docker.sock" ] ; then
        echo "DOCKER domain socket detected"
        # Do not set CRI_PATH here, we will take DOCKER domain socket
       numSocks=$((numSocks+1))
   fi
   if [ -S "/host/var/run/crio/crio.sock" ] ; then
      echo "CRIO domain socket detected"
      CRI_PATH="/var/run/crio/crio.sock"
       numSocks=$((numSocks+1))
   fi
   if [ -S "/host/run/containerd/containerd.sock" ] ; then
      echo "Containerd Domain Socket detected"
      CRI_PATH="/run/containerd/containerd.sock"
      numSocks=$((numSocks+1))
   fi
  
   if [ $numSocks -eq 0]; then
      echo "WARNING:  Unable to detect runtime container socks.  Will not be able to load container information if required."
   elif [ $numSocks -gt 1]; then
      echo "WARNING:  Multiple container runtimes detected.  This is currently unsupported.  Selecting  ${CRI_PATH}"
   fi
fi
```

**Comment by araujof** [comment]
I agree. It seems like there is a mismatch in variable names. The sanity check Teryl suggested is a good one too.

**Comment by zvn** [comment]
@terylt @araujof The change is done. Please feel free to let me know if any comments there.

thanks

**Comment by terylt** [comment]
Hey York, 

looks good.. did you get a chance to test it out with docker, containerd, crio?  If so, we can merge this in.

**Comment by zvn** [comment]
@terylt yes, tests passed

**Review by terylt — APPROVED** [review]
Looks good!

**Pull request merged**
